package com.nazaninfz.sagaorchestrator.core.enums;

public enum CommandStatus {
    INITIALIZED,

    CONDITIONS_CHECKING_STARTED,
    CONDITIONS_CHECKING_PASSED,
    CONDITIONS_CHECKING_NOT_NEEDED,
    CONDITIONS_CHECKING_FAILED,

    DECORATION_STARTED,
    DECORATION_NOT_NEEDED,
    DECORATION_FAILED,
    DECORATION_PASSED,

    COMMITTING_STARTED,
    COMMITTING_FAILED,
    COMMITTING_PASSED,
    COMMITTING_SKIPPED,

    POST_EXECUTION_STARTED,
    POST_EXECUTION_PASSED,
    POST_EXECUTION_NOT_NEEDED,
    POST_EXECUTION_FAILED,
}
