package com.nazaninfz.sagaorchestrator.core.exception;

import lombok.AllArgsConstructor;
import lombok.Getter;
import org.springframework.http.HttpStatus;

@Getter
@AllArgsConstructor
public enum SagaExceptionEnum {
    SAGA_GENERAL_EXCEPTION(HttpStatus.INTERNAL_SERVER_ERROR, 1, "SAGA_GENERAL_EXCEPTION"),
    SAGA_SAVE_COMMAND_EXCEPTION(HttpStatus.INTERNAL_SERVER_ERROR, 2, "SAGA_SAVE_COMMAND_EXCEPTION"),
    SAGA_SAVE_SEQUENCE_EXCEPTION(HttpStatus.INTERNAL_SERVER_ERROR, 3, "SAGA_SAVE_SEQUENCE_EXCEPTION"),
    SAGA_COMMAND_CONDITION_CHECKING_EXCEPTION(HttpStatus.INTERNAL_SERVER_ERROR, 4, "SAGA_COMMAND_CONDITION_CHECKING_EXCEPTION"),
    SAGA_UNSUCCESSFUL_ROLLBACK_EXCEPTION(HttpStatus.INTERNAL_SERVER_ERROR, 5, "SAGA_UNSUCCESSFUL_ROLLBACK_EXCEPTION"),
    SAGA_INPUT_DECORATION_EXCEPTION(HttpStatus.INTERNAL_SERVER_ERROR, 6, "SAGA_INPUT_DECORATION_EXCEPTION"),
    SAGA_POST_EXECUTION_EXCEPTION(HttpStatus.INTERNAL_SERVER_ERROR, 7, "SAGA_POST_EXECUTION_EXCEPTION"),
    SAGA_UNKNOWN_COMMAND_TYPE_EXCEPTION(HttpStatus.INTERNAL_SERVER_ERROR, 8, "SAGA_UNKNOWN_COMMAND_TYPE_EXCEPTION"),
    SAGA_UNSUPPORTED_OPERATION_EXCEPTION(HttpStatus.INTERNAL_SERVER_ERROR, 9, "SAGA_UNSUPPORTED_OPERATION_EXCEPTION"),

    SAGA_TIME_OUT_EXCEPTION(HttpStatus.GATEWAY_TIMEOUT, 1, "SAGA_TIME_OUT_EXCEPTION"),
    ;
    private final HttpStatus statusCode;
    private final int exceptionNumber;
    private final String message;

}
